# Generated by Django 3.2.23 on 2023-12-02 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100)),
                ('french_translation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100)),
                ('french_translation', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Vocabulary',
            new_name='Numbers',
        ),
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals', models.ManyToManyField(related_name='animals', to='vocab.Animals')),
                ('colors', models.ManyToManyField(related_name='colors', to='vocab.Colors')),
                ('numbers', models.ManyToManyField(related_name='numbers', to='vocab.Numbers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
