# Generated by Django 3.2.22 on 2023-11-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_auto_20231102_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabulary',
            name='clothes',
            field=models.ManyToManyField(related_name='clothes', to='vocab.Clothes'),
        ),
        migrations.AddField(
            model_name='uservocabulary',
            name='family',
            field=models.ManyToManyField(related_name='family', to='vocab.Family'),
        ),
        migrations.AddField(
            model_name='uservocabulary',
            name='numbers',
            field=models.ManyToManyField(related_name='numbers', to='vocab.Numbers'),
        ),
    ]
